appbasica/config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :ordens
  resources :registros
  resources :productos
  resources :clientes
  get 'ruta/saludo'
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

appbasica/app/models/orden.rb
class Orden < ApplicationRecord
    belongs_to :cliente
end

appbasica/app/controllers/ordens_controller.rb
class OrdensController < ApplicationController
  before_action :set_orden, only: [:show, :edit, :update, :destroy]

  # GET /ordens
  # GET /ordens.json
  def index
    @ordens = Orden.all
  end

  # GET /ordens/1
  # GET /ordens/1.json
  def show
  end

  # GET /ordens/new
  def new
    @orden = Orden.new
  end

  # GET /ordens/1/edit
  def edit
  end

  # POST /ordens
  # POST /ordens.json
  def create
    @orden = Orden.new(orden_params)

    respond_to do |format|
      if @orden.save
        format.html { redirect_to @orden, notice: 'Orden was successfully created.' }
        format.json { render :show, status: :created, location: @orden }
      else
        format.html { render :new }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordens/1
  # PATCH/PUT /ordens/1.json
  def update
    respond_to do |format|
      if @orden.update(orden_params)
        format.html { redirect_to @orden, notice: 'Orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @orden }
      else
        format.html { render :edit }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordens/1
  # DELETE /ordens/1.json
  def destroy
    @orden.destroy
    respond_to do |format|
      format.html { redirect_to ordens_url, notice: 'Orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orden
      @orden = Orden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orden_params
      params.require(:orden).permit(:cliente_id, :numero_orden, :fecha)
    end
end

appbasica/app/helpers/ordens_helper.rb
module OrdensHelper
end

appbasica/app/views/ordens/_form.html.erb
<%= form_with(model: orden, local: true) do |form| %>
  <% if orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden.errors.count, "error") %> prohibited this orden from being saved:</h2>

      <ul>
      <% orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.number_field :cliente_id %>
  </div>

  <div class="field">
    <%= form.label :numero_orden %>
    <%= form.number_field :numero_orden %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_select :fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appbasica/app/views/ordens/edit.html.erb
<h1>Editing Orden</h1>

<%= render 'form', orden: @orden %>

<%= link_to 'Show', @orden %> |
<%= link_to 'Back', ordens_path %>

appbasica/app/views/ordens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordens</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Numero orden</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordens.each do |orden| %>
      <tr>
        <td><%= orden.cliente_id %></td>
        <td><%= orden.numero_orden %></td>
        <td><%= orden.fecha %></td>
        <td><%= link_to 'Show', orden %></td>
        <td><%= link_to 'Edit', edit_orden_path(orden) %></td>
        <td><%= link_to 'Destroy', orden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orden', new_orden_path %>

appbasica/app/views/ordens/new.html.erb
<h1>New Orden</h1>

<%= render 'form', orden: @orden %>

<%= link_to 'Back', ordens_path %>

appbasica/app/views/ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @orden.cliente_id %>
</p>

<p>
  <strong>Numero orden:</strong>
  <%= @orden.numero_orden %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @orden.fecha %>
</p>

<%= link_to 'Edit', edit_orden_path(@orden) %> |
<%= link_to 'Back', ordens_path %>