appbasica/config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :ordens
  resources :registros
  resources :productos
  resources :clientes
  get 'ruta/saludo'
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

appbasica/app/models/detalle.rb
class Detalle < ApplicationRecord
    belongs_to :producto
end

appbasica/app/controllers/detalles_controller.rb
class DetallesController < ApplicationController
  before_action :set_detalle, only: [:show, :edit, :update, :destroy]

  # GET /detalles
  # GET /detalles.json
  def index
    @detalles = Detalle.all
  end

  # GET /detalles/1
  # GET /detalles/1.json
  def show
  end

  # GET /detalles/new
  def new
    @detalle = Detalle.new
  end

  # GET /detalles/1/edit
  def edit
  end

  # POST /detalles
  # POST /detalles.json
  def create
    @detalle = Detalle.new(detalle_params)

    respond_to do |format|
      if @detalle.save
        format.html { redirect_to @detalle, notice: 'Detalle was successfully created.' }
        format.json { render :show, status: :created, location: @detalle }
      else
        format.html { render :new }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalles/1
  # PATCH/PUT /detalles/1.json
  def update
    respond_to do |format|
      if @detalle.update(detalle_params)
        format.html { redirect_to @detalle, notice: 'Detalle was successfully updated.' }
        format.json { render :show, status: :ok, location: @detalle }
      else
        format.html { render :edit }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalles/1
  # DELETE /detalles/1.json
  def destroy
    @detalle.destroy
    respond_to do |format|
      format.html { redirect_to detalles_url, notice: 'Detalle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle
      @detalle = Detalle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detalle_params
      params.require(:detalle).permit(:producto_id, :cantidad, :precio_venta)
    end
end

appbasica/app/helpers/detalles_helper.rb
module DetallesHelper
end

appbasica/app/views/detalles/_form.html.erb
<%= form_with(model: detalle, local: true) do |form| %>
  <% if detalle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detalle.errors.count, "error") %> prohibited this detalle from being saved:</h2>

      <ul>
      <% detalle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :producto_id %>
    <%= form.number_field :producto_id %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :precio_venta %>
    <%= form.text_field :precio_venta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appbasica/app/views/detalles/edit.html.erb
<h1>Editing Detalle</h1>

<%= render 'form', detalle: @detalle %>

<%= link_to 'Show', @detalle %> |
<%= link_to 'Back', detalles_path %>

appbasica/app/views/detalles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalles</h1>

<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio venta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detalles.each do |detalle| %>
      <tr>
        <td><%= detalle.producto_id %></td>
        <td><%= detalle.cantidad %></td>
        <td><%= detalle.precio_venta %></td>
        <td><%= link_to 'Show', detalle %></td>
        <td><%= link_to 'Edit', edit_detalle_path(detalle) %></td>
        <td><%= link_to 'Destroy', detalle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detalle', new_detalle_path %>

appbasica/app/views/detalles/new.html.erb
<h1>New Detalle</h1>

<%= render 'form', detalle: @detalle %>

<%= link_to 'Back', detalles_path %>

appbasica/app/views/detalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @detalle.producto_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @detalle.cantidad %>
</p>

<p>
  <strong>Precio venta:</strong>
  <%= @detalle.precio_venta %>
</p>

<%= link_to 'Edit', edit_detalle_path(@detalle) %> |
<%= link_to 'Back', detalles_path %>